import type { DashboardData } from '../types/dashboard';
const request=async<T>(url:string,options?:RequestInit):Promise<T>=>{const isForm=options?.body instanceof FormData;const response=await fetch(url,{credentials:'include',...options,headers:{...(!isForm?{'Content-Type':'application/json'}:{}),...options?.headers}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message??'Error de conexión');return response.status===204?undefined as T:response.json()};
const withQuery=(path:string,query='')=>query?`${path}?${query}`:path;
export interface ImportPreview{token:string;hash:string;originalName:string;size:number;alreadyImported:boolean;sheetName:string;headers:string[];records:number;validRecords:number;errors:string[];errorCount:number;duplicates:number;dateFrom:string|null;dateTo:string|null;sample:{fecha:string;pv:number;numero:number;cliente:string;producto:string;total:number;saldo:number;estado:string;usuario:string}[]}
export interface SalesResponse{total:number;page:number;limit:number;pages:number;summary:{revenue:number;balance:number;averageTicket:number};filters:{statuses:string[];products:string[];users:string[]};rows:{date:string;order:string;customer:string;legalName:string;product:string;work:string;total:number;balance:number;status:string;user:string;deliveryDate:string}[]}
export interface CustomerResponse{total:number;revenue:number;withBalance:number;items:{rank:number;name:string;legalName:string;orders:number;revenue:number;balance:number;lastPurchase:string;products:number;averageTicket:number}[]}
export interface ProductResponse{total:number;revenue:number;items:{rank:number;name:string;orders:number;revenue:number;balance:number;customers:number;share:number;averageTicket:number}[]}
export interface AnalyticsResponse{source:string;records:number;revenue:number;balance:number;monthly:{name:string;value:number}[];status:{name:string;value:number}[];users:{name:string;value:number}[];ordersByUser:{name:string;value:number}[];products:{name:string;value:number}[]}
export interface ForecastResponse{generatedAt:string;source:string;method:string;training:{from:string;to:string;months:number;observedMonths:number;excludedPartialMonth:string|null;excludedOutliers:{month:string;revenue:number}[];revenueMae:number;errorPercent:number;confidence:'alta'|'media'|'baja'};history:{month:string;revenue:number;orders:number}[];forecast:{month:string;base:{revenue:number;orders:number};conservative:{revenue:number;orders:number};optimistic:{revenue:number;orders:number}}[];customers:{name:string;revenue:number;orders:number;share:number;projectedRevenue:number}[];products:{name:string;revenue:number;orders:number;share:number;projectedRevenue:number}[];limitations:string[]}
export interface ClientMetric{name:string;fantasyName:string;revenue:number;previousRevenue:number;difference:number;variation:number;orders:number;previousOrders:number;ticket:number;balance:number;frequency:number;recency:number;historicalRevenue:number;historicalOrders:number;lastPurchase:string;firstPurchase:string;products:string[];share:number;riskScore:number;rfm:{recency:number;frequency:number;monetary:number;total:number;segment:string}}
export interface ClientIntelligence{period:{from:string;to:string};comparison?:{from:string;to:string};totals:{clients:number;revenue:number;newClients:number;recovered:number;inactive:number;hhi:number};clients:ClientMetric[];rfm:{segments:{name:string;value:number}[];clients:ClientMetric[]};pareto:{clients:{name:string;revenue:number;share:number;cumulative:number;rank:number}[];thresholds:{p50:number;p80:number;p90:number};top:{top1:number;top5:number;top10:number;top20:number};hhi:number};newClients:ClientMetric[];recovered:(ClientMetric&{inactiveDays:number;returnDate:string;revenueSinceReturn:number})[];inactive:ClientMetric[];growth:{name:string;current:number;previous:number;difference:number;variation:number}[];contribution:{name:string;current:number;previous:number;difference:number;variation:number}[]}
export const clientApi={summary:(query:string,inactiveDays=90)=>request<ClientIntelligence>(`/api/analytics/clients?${query}&inactiveDays=${inactiveDays}`),detail:(name:string,query:string)=>request<ClientMetric&{status:string;timeline:{date:string;order:string;product:string;work:string;total:number;balance:number;status:string}[];evolution:{name:string;value:number}[]}>(`/api/analytics/clients/${encodeURIComponent(name)}?${query}`)};
export const api={login:(username:string,password:string)=>request<{user:{username:string;role:string}}>('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})}),logout:()=>request<void>('/api/auth/logout',{method:'POST'}),me:()=>request<{user:{username:string;role:string}}>('/api/auth/me'),dashboard:(query='')=>request<DashboardData>(withQuery('/api/dashboard',query)),previewImport:(file:File)=>{const form=new FormData();form.append('file',file);return request<ImportPreview>('/api/import/preview',{method:'POST',body:form})},confirmImport:(token:string)=>request<{message:string;records:number;originalName:string}>('/api/import/confirm',{method:'POST',body:JSON.stringify({token})}),sales:(query:string)=>request<SalesResponse>(`/api/sales?${query}`),customers:(query='')=>request<CustomerResponse>(withQuery('/api/customers',query)),products:(query='')=>request<ProductResponse>(withQuery('/api/products',query)),analytics:(query='')=>request<AnalyticsResponse>(withQuery('/api/analytics',query)),forecasts:(horizon=3)=>request<ForecastResponse>(`/api/forecasts?horizon=${horizon}`),downloadReport:async(query='')=>{const response=await fetch(withQuery('/api/reports/executive.pdf',query),{credentials:'include'});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message??'No se pudo generar el informe');return response.blob()}};
