const request=async<T>(url:string,options?:RequestInit):Promise<T>=>{const response=await fetch(url,{credentials:'include',...options,headers:{'Content-Type':'application/json',...options?.headers}});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).message??'Error de conexión');return response.json()};const withQuery=(path:string,query:string)=>query?`${path}?${query}`:path;
export interface DecisionBriefing{generatedAt:string;source:string;period:{from:string;to:string};metrics:{revenue:number;previousRevenue:number;revenueChangePercent:number;orders:number;averageTicket:number;outstanding:number;activeCustomers:number;newCustomers:number;returningCustomers:number};risks:{title:string;impact:number;evidence:string;action:string}[];opportunities:{title:string;impact:number;evidence:string;action:string}[];limitations:string[]}
export interface AIFinding{id:string;title:string;detail:string;importance:'alta'|'media'|'baja'}
export interface AIAction{id:string;action:string;reason:string;priority:1|2|3;relatedFindingIds:string[];evidenceLabels:string[]}
export interface AIEvidence{label:string;value:string;source:string;relatedFindingIds:string[]}
export interface AIAnswer{mode:'openai'|'deterministic';model?:string;answer:string;findings:AIFinding[];actions:AIAction[];evidence:AIEvidence[];limitations:string[]}
export interface AIUsage{month:string;requests:number;inputTokens:number;cachedInputTokens:number;outputTokens:number;costUsd:number}
export interface AIStatus{enabled:boolean;configured:boolean;model:string;budgetUsd:number;budgetBlocked:boolean;usage:AIUsage&{remainingUsd:number};history:AIUsage[];contextOptimization:{originalBytes:number;selectedBytes:number;reductionPercent:number}}
export const rojasAiApi={status:()=>request<AIStatus>('/api/ai/status'),briefing:(query:string)=>request<DecisionBriefing>(withQuery('/api/ai/briefing',query)),ask:async(question:string,section:string,query:string)=>{const answer=await request<AIAnswer>(withQuery('/api/ai/query',query),{method:'POST',body:JSON.stringify({question,section})});window.dispatchEvent(new Event('rojas-ai-usage-updated'));return answer}};
