import type { DashboardData, ManagerialInsight, SalesRecord, SalesRepository } from '../repositories/types.js';
import { resolvePeriod,type PeriodQuery } from '../utils/period.js';
const pct=(current:number,previous:number)=>previous===0?(current===0?0:100):((current-previous)/Math.abs(previous))*100;
const round=(value:number)=>Math.round(value*10)/10;
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const sum=(rows:SalesRecord[],key:'total'|'balance')=>rows.reduce((total,row)=>total+row[key],0);
const group=(rows:SalesRecord[],key:(row:SalesRecord)=>string,value:(row:SalesRecord)=>number=()=>1)=>{const result=new Map<string,number>();for(const row of rows)result.set(key(row),(result.get(key(row))??0)+value(row));return result};
export class AnalyticsService{
 constructor(private sales:SalesRepository){}
 async getDashboard(query:PeriodQuery):Promise<DashboardData>{
  const all=await this.sales.list();if(!all.length)throw new Error('La exportación no contiene operaciones');const periods=resolvePeriod(all,query);const current=await this.sales.list(periods.current);const previous=periods.comparison?await this.sales.list(periods.comparison):[];const revenue=sum(current,'total'),previousRevenue=sum(previous,'total'),outstanding=sum(current,'balance'),previousOutstanding=sum(previous,'balance');const activeCustomers=new Set(current.map(row=>row.customer)).size,previousCustomers=new Set(previous.map(row=>row.customer)).size;
  const revenueVariation=periods.comparison?round(pct(revenue,previousRevenue)):0;const averageTicket=current.length?revenue/current.length:0,previousTicket=previous.length?previousRevenue/previous.length:0;
  const customerSales=[...group(current,row=>row.fantasyName||row.customer,row=>row.total)].sort((a,b)=>b[1]-a[1]);const productSales=[...group(current,row=>row.product,row=>row.total)].sort((a,b)=>b[1]-a[1]);const totalProductSales=productSales.reduce((t,[,v])=>t+v,0)||1;const concentration=revenue?customerSales.slice(0,5).reduce((t,[,v])=>t+v,0)/revenue*100:0;
  const previousCustomerSales=group(previous,row=>row.customer,row=>row.total);const fallingCustomers=[...group(current,row=>row.customer,row=>row.total)].filter(([name,value])=>(previousCustomerSales.get(name)??0)>0&&pct(value,previousCustomerSales.get(name)??0)<=-20).length;
  const insights:ManagerialInsight[]=[{type:revenueVariation>=0?'positive':'alert',title:`La facturación ${revenueVariation>=0?'creció':'cayó'} ${Math.abs(revenueVariation).toLocaleString('es-AR')}%`,detail:`Comparación de ${current.length.toLocaleString('es-AR')} órdenes contra ${previous.length.toLocaleString('es-AR')} del mes anterior.`},{type:concentration>40?'alert':'positive',title:`Los 5 principales clientes concentran ${round(concentration).toLocaleString('es-AR')}%`,detail:concentration>40?'La dependencia comercial merece seguimiento.':'La cartera presenta una concentración moderada.'},{type:'opportunity',title:`${fallingCustomers} clientes redujeron compras más de 20%`,detail:'Clientes con actividad en ambos períodos que pueden requerir seguimiento comercial.'}];
  const monthly=[...group(all,row=>new Intl.DateTimeFormat('es-AR',{month:'short',year:'2-digit'}).format(row.date),row=>row.total)].map(([label,value])=>({label,value:Math.round(value/1_000_000*10)/10}));
  return {updatedAt:(await this.sales.getLastUpdated()).toISOString(),dataSource:'xlsx',sourceLabel:this.sales.getSourceLabel(),period:{from:periods.current.from!,to:periods.current.to!,previousFrom:periods.comparison?.from??'',previousTo:periods.comparison?.to??''},recordCount:current.length,kpis:{revenue,orders:current.length,averageTicket,outstanding,activeCustomers,revenueVariation,ordersVariation:periods.comparison?round(pct(current.length,previous.length)):0,averageTicketVariation:periods.comparison?round(pct(averageTicket,previousTicket)):0,outstandingVariation:periods.comparison?round(pct(outstanding,previousOutstanding)):0,activeCustomersVariation:periods.comparison?round(pct(activeCustomers,previousCustomers)):0},salesTrend:monthly,topCustomers:customerSales.slice(0,5).map(([name,value])=>({name,value})),topProducts:productSales.slice(0,5).map(([name,value])=>({name,value:round(value/totalProductSales*100)})),orderStatus:[...group(current,row=>row.status)].map(([name,value])=>({name,value})),insights};
 }
}
