import type { SalesRecord,SalesRepository } from '../repositories/types.js';
import { resolvePeriod,type PeriodQuery } from '../utils/period.js';
const sum=(r:SalesRecord[])=>r.reduce((a,x)=>a+x.total,0),iso=(d:Date)=>d.toISOString().slice(0,10),days=(a:Date,b:Date)=>Math.max(0,Math.floor((a.getTime()-b.getTime())/86400000));
const groups=(rows:SalesRecord[])=>{const m=new Map<string,SalesRecord[]>();for(const r of rows)m.set(r.customer,[...(m.get(r.customer)??[]),r]);return m};
export const rfmSegment=(r:number,f:number,m:number)=>r>=4&&f>=4&&m>=4?'VIP':r<=2&&f>=3?'En riesgo':r>=3&&f>=4?'Leales':f>=4?'Frecuentes':r>=4&&f<=2?'Nuevos':r>=4?'Prometedores':r===2?'Dormidos':'Perdidos';
const score=(value:number,sorted:number[],reverse=false)=>{const rank=sorted.filter(x=>x<=value).length/Math.max(1,sorted.length);const s=Math.min(5,Math.max(1,Math.ceil(rank*5)));return reverse?6-s:s};
export class ClientIntelligenceService{
 constructor(private sales:SalesRepository){}
 async summary(query:PeriodQuery,inactiveDays=90){const all=await this.sales.list(),periods=resolvePeriod(all,query),current=await this.sales.list(periods.current),previous=periods.comparison?await this.sales.list(periods.comparison):[],latest=new Date(periods.current.to+'T23:59:59'),allGroups=groups(all),curGroups=groups(current),prevGroups=groups(previous),totalRevenue=sum(current);
  const base=[...allGroups].map(([name,history])=>{history.sort((a,b)=>a.date.getTime()-b.date.getTime());const cur=curGroups.get(name)??[],prev=prevGroups.get(name)??[],revenue=sum(cur),previousRevenue=sum(prev),frequency=cur.length,last=history.at(-1)!.date,recency=days(latest,last),historicalRevenue=sum(history),historicalOrders=history.length,balance=history.reduce((a,x)=>a+x.balance,0);return{name,fantasyName:history.find(x=>x.fantasyName)?.fantasyName??name,revenue,previousRevenue,difference:revenue-previousRevenue,variation:previousRevenue?(revenue-previousRevenue)/previousRevenue*100:null,orders:frequency,previousOrders:prev.length,ticket:frequency?revenue/frequency:0,balance,frequency,recency,historicalRevenue,historicalOrders,lastPurchase:iso(last),firstPurchase:iso(history[0]!.date),products:[...new Set(cur.map(x=>x.product))],share:totalRevenue?revenue/totalRevenue*100:0}});
  const recencies=base.map(x=>x.recency).sort((a,b)=>a-b),frequencies=base.map(x=>x.historicalOrders).sort((a,b)=>a-b),monetaries=base.map(x=>x.historicalRevenue).sort((a,b)=>a-b);
  const clients=base.map(x=>{const r=score(x.recency,recencies,true),f=score(x.historicalOrders,frequencies),m=score(x.historicalRevenue,monetaries);return{...x,rfm:{recency:r,frequency:f,monetary:m,total:r+f+m,segment:rfmSegment(r,f,m)},riskScore:Math.round(Math.min(100,(Math.min(x.recency/Math.max(1,inactiveDays),2)*30)+(m*6)+(f*4)+(x.difference<0?Math.min(30,Math.abs(x.difference)/Math.max(1,x.previousRevenue)*30):0)))}}).sort((a,b)=>b.revenue-a.revenue);
  const active=clients.filter(x=>curGroups.has(x.name)),newClients=active.filter(x=>x.firstPurchase>=periods.current.from!&&x.firstPurchase<=periods.current.to!),recovered=active.flatMap(x=>{const h=allGroups.get(x.name)!.slice().sort((a,b)=>a.date.getTime()-b.date.getTime());const returns=h.map((v,i)=>i?{gap:days(v.date,h[i-1]!.date),date:v.date}:null).filter(Boolean) as {gap:number;date:Date}[];const hit=returns.find(v=>v.gap>=inactiveDays&&iso(v.date)>=periods.current.from!&&iso(v.date)<=periods.current.to!);return hit?[{...x,inactiveDays:hit.gap,returnDate:iso(hit.date),revenueSinceReturn:sum(h.filter(v=>v.date>=hit.date))}]:[]}),inactive=clients.filter(x=>x.recency>=inactiveDays).sort((a,b)=>b.riskScore-a.riskScore);
  let accumulated=0;const pareto=active.map((x,i)=>{accumulated+=x.revenue;return{name:x.name,revenue:x.revenue,share:x.share,cumulative:totalRevenue?accumulated/totalRevenue*100:0,rank:i+1}}),reach=(n:number)=>pareto.find(x=>x.cumulative>=n)?.rank??0;const hhi=active.reduce((a,x)=>a+x.share*x.share,0);
  const contribution=clients.filter(x=>x.revenue||x.previousRevenue).sort((a,b)=>Math.abs(b.difference)-Math.abs(a.difference)).map(x=>({name:x.name,current:x.revenue,previous:x.previousRevenue,difference:x.difference,variation:x.variation}));
  const segments=Object.entries(clients.reduce<Record<string,number>>((a,x)=>(a[x.rfm.segment]=(a[x.rfm.segment]??0)+1,a),{})).map(([name,value])=>({name,value}));
  return{period:periods.current,comparison:periods.comparison,totals:{clients:active.length,revenue:totalRevenue,newClients:newClients.length,recovered:recovered.length,inactive:inactive.length,hhi},clients,rfm:{segments,clients},pareto:{clients:pareto,thresholds:{p50:reach(50),p80:reach(80),p90:reach(90)},top:{top1:pareto.slice(0,1).reduce((a,x)=>a+x.share,0),top5:pareto.slice(0,5).reduce((a,x)=>a+x.share,0),top10:pareto.slice(0,10).reduce((a,x)=>a+x.share,0),top20:pareto.slice(0,20).reduce((a,x)=>a+x.share,0)},hhi},newClients,recovered,inactive,growth:contribution,contribution};
 }
 async detail(name:string,query:PeriodQuery){const data=await this.summary(query);const client=data.clients.find(x=>x.name===name);if(!client)return null;const all=(await this.sales.list()).filter(x=>x.customer===name).sort((a,b)=>b.date.getTime()-a.date.getTime());const monthly=new Map<string,number>();for(const r of all){const k=iso(r.date).slice(0,7);monthly.set(k,(monthly.get(k)??0)+r.total)}return{...client,status:client.recency>=90?'Inactivo':client.difference<0?'En seguimiento':'Activo',timeline:all.map(x=>({date:iso(x.date),order:`${x.pointOfSale}-${x.number}`,product:x.product,work:x.work,total:x.total,balance:x.balance,status:x.status})),evolution:[...monthly].map(([name,value])=>({name,value})).sort((a,b)=>a.name.localeCompare(b.name))}}
}
