import type { SalesRecord } from '../repositories/types.js';

export type CustomerSegment='imprenta'|'disenador'|'publico';
export const DESIGNER_CATALOG_VERSION='2026-09-28';
export const PRINTER_CATALOG_VERSION='2026-09-28';
export const DESIGNER_CUSTOMERS=[
 'ACOSTA YAMILA','ANALIA MUÑOZ','ANCHERAMA RICARDO ESTEBAN','ARIJON ALICIA','AVILA ANTONELA','BARROSO YANINA','BEILMANN BARBARA','BELTRAME SANDRA','BERMUDEZ FERNANDO','BIANCHI LILIANA','BIBLIOTECA RODOLFO GARCIA','BLANCO ALEJANDRA','BOURLOT CHIARA','CAMPOSTRINI BERENICE','DELASOIE SHEILA','ECHEPARE MELINA','ERNST JORGELINA','EULER JENNIFER','FANDRICH BARBARA','FUENTES ROGELIO M','GALETTO SOFIA','GARCIA CINTIA','GAUNA CRISTIAN','GODOY DENISE','GRANE EUGENIA','GRANE IVANA','GUIDO DANIEL','HIDALGO FLAVIA','LEMA NATALIA','LEMIÑA MARIANA','LIZZI SEBASTIAN','LUJAN FLORENCIA','LUJAN JESICA','LUPI LAUTARO','MAELHO S.R.L.','MAELHO SA','MAGALLAN WALTER','MARECO GONZALEZ LUCIA','MARIA JESUS VULLIEZ','MARTINETTI DELFINA','MEDRANO IBERIA','MENNA ILEANA - CABAÑAS DEL VIÑEDO','MEYER LETICIA','MONTENEGRO JUAN','MUÑOZ CAROLINA','OBISPADO GUALEGUAYCHU','OTERO JULIETA','PAIS ROMINA','PAOLA FERNANDEZ','PEREYRA ALAN','PEREZ NATALIA','PETRONIO SOFIA','PICO PUYADE VALERIA KARINA','PIRI EVELYN','RAMIREZ FABIAN','RIEHME CYNTHIA','RIVAROLA PAMELA','ROMERO JUAN IGNACIO','SANNA ANTONELLA','SANTOS DANIEL','SELVA GUADALUPE','SOBRINO LUCIA','SPIAZZI ANDRES','VACCARI VIRGINIA','VASILCHICOF ROMINA','VILLANOVA ALONSO','ZAVALA NATALIA','MONRROY BELEN','GUTIERREZ GUADALUPE','MANTEGAZZA ALEJO'
] as const;

export const PRINTER_CUSTOMERS=[
 'ALAN RUBEN DALMAO','ALBA RENZO','ALBORNOZ SUSANA','AMARILLO LUJAN','BALLAY ADRIAN','BARBOZA GUILLERMO','BENITEZ JOAQUIN DANIEL - IMPRENTA','BENTANCOUR GUILLERMO','BOUJON HECTOR','CARMODY JOSE','CASTRO FERNANDO','CIUCIO AGUSTIN','CLAA RODRIGO','COPYCENTER CONCORDIA','ESCALANTE CESAR - IMPRENTA COLON','GOÑI JUAN PABLO','IMPRENTA PIÑEYRO','IMPRENTA ROBERT SRL','IMPRENTA VENUS','KOLMAN HUGO','LOPEZ JUAN PABLO','MANTEGAZZA JUAN','MELGAREJO NESTOR','PEREYRA WALTER','PIROLLA PAUL','QUIJANO BENEGAS NICOLAS','QUIROS ALEJANDRO','REMOLIF PABLO','ROJAS IMPRESIONES','RUIZ FABRICIO','ZIMMERMANN DANIEL','ZORRO PIÑEYRO IMPRENTA','IMAGEN DIGITAL','GERA','JUAN MANTEGAZZA - IMPRENTA','LEONEL PITER','TATU','EMMANUEL LA PAZ','AILEN VILLAVERDE','ARACELI BROTZMAN','BRUNO BRUZZONI','HUMBERTO RAMIREZ','AILU','MILI','EMA','ARA','BRUZZONI BRUNO','LEO','EFECTO VISUAL','PINO / PIPI','GREISING CONCEPCION','REICHEL FRANCO'
] as const;
const DESIGNER_ALIASES=['LILI BIANCHI'] as const;
const PRINTER_ALIASES=['PINO','PIPI'] as const;
export const normalizeCustomerName=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const catalogMatch=(value:string,catalog:readonly string[])=>catalog.some(item=>{const alias=normalizeCustomerName(item);return value===alias||value.startsWith(`${alias} `)||value.endsWith(` ${alias}`)||value.includes(` ${alias} `)});

export function classifyCustomer(row:Pick<SalesRecord,'customer'|'fantasyName'>):CustomerSegment{
 const legal=normalizeCustomerName(row.customer),fantasy=normalizeCustomerName(row.fantasyName??''),values=[legal,fantasy].filter(Boolean);
 if(values.some(value=>catalogMatch(value,PRINTER_CUSTOMERS)||catalogMatch(value,PRINTER_ALIASES)))return'imprenta';
 if(values.some(value=>catalogMatch(value,DESIGNER_CUSTOMERS)||catalogMatch(value,DESIGNER_ALIASES)))return'disenador';
 const combined=values.join(' ');
 if(/\b(imprenta|grafi|impresora|editorial|serigraf)/.test(combined))return'imprenta';
 if(/\b(diseno|disenador|agencia|publicidad|estudio creativo)/.test(combined))return'disenador';
 return'publico';
}
