import type { SalesRecord,SalesRepository } from '../repositories/types.js';

type Point={month:string;revenue:number;orders:number};
type CandidateName='promedio_movil_3'|'promedio_ponderado'|'tendencia_lineal';
const monthKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;
const addMonths=(month:string,amount:number)=>{const [year,number]=month.split('-').map(Number),date=new Date(year!,number!-1+amount,1);return monthKey(date)};
const clamp=(value:number)=>Math.max(0,value);
const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]!:(sorted[middle-1]!+sorted[middle]!)/2};
const withoutExtremeOutliers=(points:Point[],field:'revenue'|'orders')=>{const center=median(points.map(point=>point[field]));return points.filter(point=>!center||(point[field]>=center/3&&point[field]<=center*3))};
const regression=(values:number[])=>{const n=values.length,xMean=(n-1)/2,yMean=mean(values),denominator=values.reduce((sum,_value,index)=>sum+(index-xMean)**2,0),slope=denominator?values.reduce((sum,value,index)=>sum+(index-xMean)*(value-yMean),0)/denominator:0,intercept=yMean-slope*xMean,fitted=values.map((_value,index)=>clamp(intercept+slope*index)),mae=mean(values.map((value,index)=>Math.abs(value-fitted[index]!)));return{slope,intercept,mae,predict:(index:number)=>clamp(intercept+slope*index)}};
const candidatePrediction=(name:CandidateName,history:number[])=>{if(name==='promedio_movil_3')return mean(history.slice(-3));if(name==='promedio_ponderado'){const values=history.slice(-6),weights=values.map((_value,index)=>index+1),weightTotal=weights.reduce((sum,value)=>sum+value,0);return values.reduce((sum,value,index)=>sum+value*weights[index]!,0)/weightTotal}return regression(history).predict(history.length)};
const individualProjection=(series:number[])=>{
 const activeMonths=series.filter(value=>value>0).length,lastActiveIndex=series.reduce((found,value,index)=>value>0?index:found,-1),recencyMonths=lastActiveIndex<0?series.length:series.length-1-lastActiveIndex,average=mean(series);
 if(activeMonths<2){const projected=average;return{projected,model:'promedio_mensual_con_ceros',mae:null,errorPercent:null,confidence:'baja' as const,activeMonths,recencyMonths,trend:'historial insuficiente',low:clamp(projected*.5),high:projected*1.5}}
 const candidates:CandidateName[]=['promedio_movil_3','promedio_ponderado','tendencia_lineal'],evaluated=candidates.map((name,priority)=>{const errors:number[]=[];for(let index=3;index<series.length;index++)errors.push(Math.abs(series[index]!-candidatePrediction(name,series.slice(0,index))));return{name,priority,mae:errors.length?mean(errors):Number.POSITIVE_INFINITY,predicted:candidatePrediction(name,series)}}).sort((a,b)=>a.mae-b.mae||a.priority-b.priority),winner=evaluated[0]!,fallback=!Number.isFinite(winner.mae),projected=fallback?average:winner.predicted,mae=fallback?null:winner.mae,errorPercent=mae===null||!average?null:mae/average*100,confidence=series.length>=12&&activeMonths>=6&&(errorPercent??Infinity)<=25?'alta':series.length>=6&&activeMonths>=3&&(errorPercent??Infinity)<=50?'media':'baja',slope=regression(series).slope,trendRatio=average?slope/average:0,trend=trendRatio>.1?'creciente':trendRatio<-.1?'decreciente':'estable',uncertainty=Math.max(mae??projected*.35,projected*.15);
 return{projected,model:fallback?'promedio_mensual_con_ceros':winner.name,mae,errorPercent,confidence,activeMonths,recencyMonths,trend,low:clamp(projected-uncertainty),high:projected+uncertainty};
};

export class ForecastService{
 constructor(private sales:SalesRepository){}
 async forecast(horizon=3){
  const rows=await this.sales.list();if(!rows.length)throw new Error('No hay datos para proyectar');
  const latest=new Date(Math.max(...rows.map(row=>row.date.getTime()))),first=new Date(Math.min(...rows.map(row=>row.date.getTime()))),lastDay=new Date(latest.getFullYear(),latest.getMonth()+1,0).getDate(),latestComplete=latest.getDate()===lastDay,finalTrainingMonth=latestComplete?monthKey(latest):addMonths(monthKey(latest),-1),map=new Map<string,Point>();
  for(const row of rows){const key=monthKey(row.date);if(key>finalTrainingMonth)continue;const point=map.get(key)??{month:key,revenue:0,orders:0};point.revenue+=row.total;point.orders++;map.set(key,point)}
  const months:string[]=[];for(let key=monthKey(first);key<=finalTrainingMonth;key=addMonths(key,1))months.push(key);
  const history=months.map(month=>map.get(month)??{month,revenue:0,orders:0}).slice(-18),training=history.slice(-12);if(training.length<3)throw new Error('Se necesitan al menos 3 meses completos para generar una proyección verificable');
  const cleanRevenue=withoutExtremeOutliers(training,'revenue'),cleanOrders=withoutExtremeOutliers(training,'orders');if(cleanRevenue.length<3)throw new Error('No hay al menos 3 meses comparables después de controlar valores atípicos');
  const revenueModel=regression(cleanRevenue.map(point=>point.revenue)),ordersModel=regression(cleanOrders.map(point=>point.orders)),avgRevenue=mean(cleanRevenue.map(point=>point.revenue)),errorPercent=avgRevenue?revenueModel.mae/avgRevenue*100:100,confidence=cleanRevenue.length>=12&&errorPercent<=20?'alta':cleanRevenue.length>=6&&errorPercent<=40?'media':'baja',forecast=Array.from({length:horizon},(_value,index)=>{const revenue=revenueModel.predict(cleanRevenue.length+index),orders=ordersModel.predict(cleanOrders.length+index),uncertainty=Math.max(revenueModel.mae,revenue*.1)*Math.sqrt(index+1),orderUncertainty=Math.max(ordersModel.mae,orders*.1)*Math.sqrt(index+1);return{month:addMonths(finalTrainingMonth,index+1),base:{revenue:Math.round(revenue),orders:Math.round(orders)},conservative:{revenue:Math.round(clamp(revenue-uncertainty)),orders:Math.round(clamp(orders-orderUncertainty))},optimistic:{revenue:Math.round(revenue+uncertainty),orders:Math.round(orders+orderUncertainty)}}});
  const recentFrom=addMonths(finalTrainingMonth,-2),recent=rows.filter(row=>{const key=monthKey(row.date);return key>=recentFrom&&key<=finalTrainingMonth}),recentRevenue=recent.reduce((sum,row)=>sum+row.total,0),trainingMonths=training.map(point=>point.month);
  const projectEntities=(keyOf:(row:SalesRecord)=>string)=>{const entities=new Map<string,{name:string;revenue:number;orders:number;monthly:Map<string,number>}>();for(const row of rows){const month=monthKey(row.date);if(month>finalTrainingMonth||!trainingMonths.includes(month))continue;const name=keyOf(row),item=entities.get(name)??{name,revenue:0,orders:0,monthly:new Map<string,number>()};item.monthly.set(month,(item.monthly.get(month)??0)+row.total);entities.set(name,item)}for(const row of recent){const name=keyOf(row),item=entities.get(name);if(item){item.revenue+=row.total;item.orders++}}return[...entities.values()].map(item=>{const series=trainingMonths.map(month=>item.monthly.get(month)??0),projection=individualProjection(series);return{name:item.name,revenue:Math.round(item.revenue),orders:item.orders,share:recentRevenue?item.revenue/recentRevenue*100:0,projectedRevenue:Math.round(projection.projected),projectionMethod:projection.model,projectionMae:projection.mae===null?null:Math.round(projection.mae),projectionErrorPercent:projection.errorPercent===null?null:Number(projection.errorPercent.toFixed(1)),projectionConfidence:projection.confidence,activeMonths:projection.activeMonths,historyMonths:series.length,recencyMonths:projection.recencyMonths,trend:projection.trend,projectionRange:{low:Math.round(projection.low),high:Math.round(projection.high)}}}).sort((a,b)=>b.projectedRevenue-a.projectedRevenue)};
  const customers=projectEntities(row=>row.fantasyName||row.customer).slice(0,50),products=projectEntities(row=>row.product).slice(0,50);
  return{generatedAt:new Date().toISOString(),source:this.sales.getSourceLabel(),method:'Proyección general por tendencia robusta. Clientes y productos: promedio móvil, promedio ponderado y tendencia lineal con backtesting; se elige el menor error individual sin ajuste proporcional.',training:{from:training[0]!.month,to:training.at(-1)!.month,months:cleanRevenue.length,observedMonths:training.length,excludedPartialMonth:latestComplete?null:monthKey(latest),excludedOutliers:training.filter(point=>!cleanRevenue.includes(point)).map(point=>({month:point.month,revenue:Math.round(point.revenue)})),revenueMae:Math.round(revenueModel.mae),errorPercent:Number(errorPercent.toFixed(1)),confidence},history,forecast,customers,products,individualProjection:{models:['promedio_movil_3','promedio_ponderado','tendencia_lineal'],selection:'Menor error absoluto medio en backtesting temporal.',zeroMonthsIncluded:true,reconciledToGeneralForecast:false,customerProjectionSum:customers.reduce((sum,item)=>sum+item.projectedRevenue,0),productProjectionSum:products.reduce((sum,item)=>sum+item.projectedRevenue,0)},limitations:['La proyección refleja patrones históricos y no garantiza resultados futuros.','Con sólo cinco meses completos, la confianza individual permanece baja; la estacionalidad requiere al menos 18 a 24 meses.','Los clientes con menos de dos meses activos usan un promedio mensual conservador con meses sin compras en cero.','Las proyecciones individuales no se fuerzan a coincidir con el pronóstico general.','No incorpora costos, margen, campañas, capacidad productiva ni cambios externos porque el Excel no contiene esas variables.','Los meses incompletos se excluyen del entrenamiento y se informan expresamente.']};
 }
}
