import type { SalesRecord } from '../repositories/types.js';

const months=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const round=(value:number)=>Math.round(value*100)/100;
type Dimension='customer'|'product'|'user'|'status'|'pointOfSale'|'work';

const aggregate=(rows:SalesRecord[])=>{const revenue=rows.reduce((sum,row)=>sum+row.total,0),balance=rows.reduce((sum,row)=>sum+row.balance,0);return{revenue:round(revenue),balance:round(balance),orders:rows.length,activeCustomers:new Set(rows.map(row=>row.customer)).size,averageTicket:rows.length?round(revenue/rows.length):0}};
const dimensionConfig:Record<Dimension,{label:string;pattern:RegExp;key:(row:SalesRecord)=>string}>={customer:{label:'Cliente',pattern:/\bclientes?\b|comprador/,key:row=>row.customer},product:{label:'Producto',pattern:/\bproductos?\b|servicio/,key:row=>row.product},user:{label:'Usuario',pattern:/\busuarios?\b/,key:row=>row.user},status:{label:'Estado',pattern:/\bestados?\b/,key:row=>row.status},pointOfSale:{label:'PV',pattern:/\bpv\b|punto de venta/,key:row=>String(row.pointOfSale)},work:{label:'Trabajo',pattern:/\btrabajos?\b|descripcion/,key:row=>row.work}};
const groupRows=(rows:SalesRecord[],dimension:Dimension)=>{const groups=new Map<string,SalesRecord[]>();for(const row of rows){const key=dimensionConfig[dimension].key(row)||'(vacío)';groups.set(key,[...(groups.get(key)??[]),row])}return[...groups].map(([name,items])=>({name,...aggregate(items)})).sort((a,b)=>b.revenue-a.revenue).slice(0,100)};

export function buildRelationalQuestionData(allRows:SalesRecord[],fallbackRows:SalesRecord[],question:string){
 if(!allRows.length)return null;const q=normalize(question),latest=allRows.reduce((max,row)=>row.date>max?row.date:max,allRows[0]!.date),globalYears=[...q.matchAll(/\b(20\d{2})\b/g)].map(match=>Number(match[1])),periodMatches=[...q.matchAll(new RegExp(`\\b(${months.join('|')})(?:\\s+(?:de\\s+)?(20\\d{2}))?`,'g'))],seen=new Set<string>(),periods=periodMatches.flatMap(match=>{const month=months.indexOf(match[1]!),explicitYear=match[2]?Number(match[2]):globalYears.length===1?globalYears[0]!:undefined,year=explicitYear??(month<=latest.getMonth()?latest.getFullYear():latest.getFullYear()-1),key=`${year}-${month}`;if(seen.has(key))return[];seen.add(key);const rows=allRows.filter(row=>row.date.getFullYear()===year&&row.date.getMonth()===month),lastDay=new Date(year,month+1,0).getDate(),latestAvailable=rows.length?Math.max(...rows.map(row=>row.date.getDate())):0,complete=year<latest.getFullYear()||(year===latest.getFullYear()&&month<latest.getMonth())||latestAvailable===lastDay;return[{key,label:`${months[month]} ${year}`,from:iso(new Date(year,month,1)),to:iso(new Date(year,month,complete?lastDay:latestAvailable||lastDay)),complete,rows}]}),requestedMeasures=[...new Set([/recaud|factur|venta|ingreso|\btotal\b/.test(q)?'revenue':null,/saldo|cobr/.test(q)?'balance':null,/orden|pedido|operacion/.test(q)?'orders':null,/ticket/.test(q)?'averageTicket':null,/clientes? activos|cantidad de clientes/.test(q)?'activeCustomers':null].filter((value):value is string=>Boolean(value)))];if(periods.length&&!requestedMeasures.length)requestedMeasures.push('revenue');
 const requestedDimensions=(Object.entries(dimensionConfig) as [Dimension,(typeof dimensionConfig)[Dimension]][]).filter(([,config])=>config.pattern.test(q)).map(([dimension])=>dimension),unique=(selector:(row:SalesRecord)=>string)=>[...new Set(allRows.map(selector).filter(value=>value&&normalize(value).length>=3))],entityValues={customer:unique(row=>row.customer),fantasyName:unique(row=>row.fantasyName??''),product:unique(row=>row.product),user:unique(row=>row.user),status:unique(row=>row.status)},matches=(values:string[])=>values.filter(value=>q.includes(normalize(value))).sort((a,b)=>b.length-a.length).slice(0,10),matchedFilters={customers:matches(entityValues.customer),fantasyNames:matches(entityValues.fantasyName),products:matches(entityValues.product),users:matches(entityValues.user),statuses:matches(entityValues.status)},hasFilters=Object.values(matchedFilters).some(values=>values.length>0),matchesAllFilters=(row:SalesRecord)=>{const customerFilters=[...matchedFilters.customers,...matchedFilters.fantasyNames],customerMatches=!customerFilters.length||matchedFilters.customers.includes(row.customer)||matchedFilters.fantasyNames.includes(row.fantasyName??'');return customerMatches&&(!matchedFilters.products.length||matchedFilters.products.includes(row.product))&&(!matchedFilters.users.length||matchedFilters.users.includes(row.user))&&(!matchedFilters.statuses.length||matchedFilters.statuses.includes(row.status))},baseRows=periods.length?periods.flatMap(period=>period.rows):fallbackRows,filteredRows=hasFilters?baseRows.filter(matchesAllFilters):baseRows,periodResults=periods.map(period=>{const rows=hasFilters?period.rows.filter(matchesAllFilters):period.rows;return{label:period.label,from:period.from,to:period.to,complete:period.complete,recordsUsed:rows.length,metrics:aggregate(rows),groupedBy:Object.fromEntries(requestedDimensions.map(dimension=>[dimension,groupRows(rows,dimension)]))}}),matched=Boolean(periods.length||requestedMeasures.length||requestedDimensions.length||hasFilters);if(!matched)return null;
 return{matched,interpretation:{requestedMeasures,requestedDimensions,matchedFilters,scope:periods.length?'Meses mencionados en la pregunta':'Período global seleccionado'},dataDictionary:{Fecha:'Fecha de la operación',PV:'Punto de venta',Número:'Número de operación',Cliente:'Razón social',NombreFantasía:'Nombre comercial',FechaEntrega:'Fecha de entrega registrada',Producto:'Categoría de producto',Trabajo:'Descripción original',Total:'Facturación registrada de la operación',Saldo:'Saldo registrado; no implica deuda vencida',Estado:'Estado de la operación',Usuario:'Usuario asociado a la operación'},relationship:'Todas las columnas pertenecen a la misma operación y se relacionan por su fila; PV + Número identifica la orden en la exportación.',periods:periodResults,overall:{recordsUsed:filteredRows.length,metrics:aggregate(filteredRows),groupedBy:Object.fromEntries(requestedDimensions.map(dimension=>[dimension,groupRows(filteredRows,dimension)]))},operations:hasFilters?filteredRows.slice().sort((a,b)=>b.date.getTime()-a.date.getTime()).slice(0,50).map(row=>({date:iso(row.date),order:`${row.pointOfSale}-${row.number}`,customer:row.customer,fantasyName:row.fantasyName,deliveryDate:iso(row.deliveryDate),product:row.product,work:row.work,total:round(row.total),balance:round(row.balance),status:row.status,user:row.user})):[],formulae:{revenue:'SUM(Total)',balance:'SUM(Saldo)',orders:'COUNT(filas)',activeCustomers:'COUNT(DISTINCT Cliente)',averageTicket:'SUM(Total) / COUNT(filas)'},limitations:[...(q.includes('recaud')?['La exportación no posee una columna de cobros: “recaudado” se interpreta como facturación registrada en Total, no como dinero efectivamente cobrado.']:[]),'Saldo no contiene vencimiento suficiente para afirmar mora.','Órdenes son operaciones registradas, no unidades físicas.']};
}
