export type WorkExtraction={material:string|null;variant:string|null;techniques:string[];finishes:string[];colors:string[];quantity:number|null;quantityUnit:string|null;dimensions:{width:number;height:number;unit:string;areaM2:number|null}|null};
export const normalizeWork=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
const firstMatch=(value:string,rules:[RegExp,string][])=>rules.find(([pattern])=>pattern.test(value))?.[1]??null;
const allMatches=(value:string,rules:[RegExp,string][])=>rules.filter(([pattern])=>pattern.test(value)).map(([,label])=>label);
const materials:[RegExp,string][]=[[/\bvinilo\b/,'Vinilo'],[/\blona\b|\bbanner\b/,'Lona / banner'],[/\bpvc\b/,'PVC'],[/\bacrilic/,'Acrílico'],[/\biman|imantad/,'Imán'],[/\bpapel\b/,'Papel'],[/cartulin/,'Cartulina'],[/opalin/,'Opalina'],[/poliprop/,'Polipropileno'],[/\btela\b/,'Tela'],[/\bchap[a-z]*\b/,'Chapa'],[/\bfoam\b|foamboard/,'Foamboard']];
const techniques:[RegExp,string][]=[[/impresion uv|impreso uv|\buv\b/,'Impresión UV'],[/eco[ -]?solvente/,'Ecosolvente'],[/\boffset\b/,'Offset'],[/\blaser\b/,'Láser'],[/sublim/,'Sublimación'],[/serigraf/,'Serigrafía']];
const finishes:[RegExp,string][]=[[/laminad/,'Laminado'],[/plastific/,'Plastificado'],[/troquel/,'Troquelado'],[/corte profundo/,'Corte profundo'],[/medio corte/,'Medio corte'],[/corte recto/,'Corte recto'],[/\bplegad/,'Plegado'],[/encuadern/,'Encuadernado'],[/\bojales?\b/,'Ojales'],[/barniz/,'Barniz']];
const colors:[RegExp,string][]=[[/\bnegro\b/,'Negro'],[/\bblanco\b/,'Blanco'],[/\bazul\b/,'Azul'],[/\brojo\b/,'Rojo'],[/\bverde\b/,'Verde'],[/\bdorado\b/,'Dorado'],[/\bplateado\b/,'Plateado'],[/\bamarillo\b/,'Amarillo'],[/\bmagenta\b/,'Magenta']];
const toNumber=(value:string)=>Number(value.replace(',','.'));
const dimensionFactor=(unit:string)=>unit==='mm'?.001:unit==='cm'?.01:1;
export function extractWorkText(text:string):WorkExtraction{const value=normalizeWork(text);const material=firstMatch(value,materials);let variant:string|null=null;if(material==='Vinilo'){variant=firstMatch(value,[[/holograf/,'Holográfico'],[/esmeril/,'Esmerilado'],[/microperfor/,'Microperforado'],[/reflectiv/,'Reflectivo'],[/clear|transparent/,'Transparente / clear'],[/base gris/,'Base gris'],[/de corte|vinilo corte/,'De corte'],[/impreso|impresion/,'Impreso']])}
 const dimension=value.match(/(\d+(?:[.,]\d+)?)\s*(mm|cm|mts?|metros?|m)?\s*(?:x|por)\s*(\d+(?:[.,]\d+)?)\s*(mm|cm|mts?|metros?|m)/i);let dimensions:WorkExtraction['dimensions']=null;if(dimension){const width=toNumber(dimension[1]!),height=toNumber(dimension[3]!),rawFirst=dimension[2]??dimension[4]!,rawSecond=dimension[4]!,unit=(rawFirst.startsWith('m')&&!rawFirst.startsWith('mm'))?'m':rawFirst,secondUnit=(rawSecond.startsWith('m')&&!rawSecond.startsWith('mm'))?'m':rawSecond;dimensions={width,height,unit:`${unit} x ${secondUnit}`,areaM2:Number((width*dimensionFactor(unit)*height*dimensionFactor(secondUnit)).toFixed(4))}}
 const quantityMatch=value.match(/(?:cantidad\s*[:=]?\s*)?(\d+)\s*(unidades?|unds?\.?|copias?|planchas?|carteles?|stickers?|etiquetas?|calcos?)/i);return{material,variant,techniques:allMatches(value,techniques),finishes:allMatches(value,finishes),colors:allMatches(value,colors),quantity:quantityMatch?Number(quantityMatch[1]):null,quantityUnit:quantityMatch?.[2]??null,dimensions}}
export function aggregateExtractions(texts:string[]){const extracted=texts.map(extractWorkText),ranking=(values:(string|null)[])=>{const map=new Map<string,number>();for(const value of values)if(value)map.set(value,(map.get(value)??0)+1);return[...map].map(([name,orders])=>({name,orders})).sort((a,b)=>b.orders-a.orders)};return{analyzedOperations:texts.length,withMaterial:extracted.filter(x=>x.material).length,withDeclaredQuantity:extracted.filter(x=>x.quantity!==null).length,withDimensions:extracted.filter(x=>x.dimensions).length,materials:ranking(extracted.map(x=>x.material)),variants:ranking(extracted.map(x=>x.variant)),techniques:ranking(extracted.flatMap(x=>x.techniques)),finishes:ranking(extracted.flatMap(x=>x.finishes)),colors:ranking(extracted.flatMap(x=>x.colors)),declaredQuantityTotal:extracted.reduce((sum,x)=>sum+(x.quantity??0),0),knownAreaM2:Number(extracted.reduce((sum,x)=>sum+(x.dimensions?.areaM2??0)*(x.quantity??1),0).toFixed(2))}}
