import { Router } from 'express';
import { z } from 'zod';
import ExcelJS from 'exceljs';
import { salesRepository } from '../repositories/index.js';
import { DataExplorerService } from '../services/DataExplorerService.js';
import { ClientIntelligenceService } from '../services/ClientIntelligenceService.js';
import { ForecastService } from '../services/ForecastService.js';
import { ReportService } from '../services/ReportService.js';
import { periodQuerySchema, resolvePeriod } from '../utils/period.js';

const service=new DataExplorerService(salesRepository);
const clientIntelligence=new ClientIntelligenceService(salesRepository);
const forecasts=new ForecastService(salesRepository);
const reports=new ReportService(salesRepository);
const salesQuerySchema=periodQuerySchema.extend({search:z.string().optional().default(''),status:z.string().optional().default(''),product:z.string().optional().default(''),user:z.string().optional().default(''),customerType:z.enum(['imprenta','disenador','publico']).optional(),minTotal:z.coerce.number().nonnegative().optional(),maxTotal:z.coerce.number().nonnegative().optional(),page:z.coerce.number().int().positive().default(1),limit:z.coerce.number().int().min(10).max(100).default(50)}).refine(query=>query.minTotal===undefined||query.maxTotal===undefined||query.minTotal<=query.maxTotal,{message:'El total mínimo no puede superar al máximo'});
const currentPeriod=async(query:unknown)=>resolvePeriod(await salesRepository.list(),periodQuerySchema.parse(query)).current;
export const dataRouter=Router();

dataRouter.get('/sales/export.xlsx',async(req,res,next)=>{try{const query=salesQuerySchema.parse(req.query),period=resolvePeriod(await salesRepository.list(),query).current,rows=await service.salesExport({...query,period});const workbook=new ExcelJS.Workbook();workbook.creator='Rojas Intelligence';workbook.created=new Date();const summary=workbook.addWorksheet('Resumen'),sheet=workbook.addWorksheet('Ventas');summary.columns=[{width:28},{width:34}];summary.addRows([['REPORTE DE VENTAS FILTRADAS',''],['Período',`${period.from} a ${period.to}`],['Operaciones',rows.length],['Facturación',rows.reduce((total,row)=>total+row.total,0)],['Saldo',rows.reduce((total,row)=>total+row.balance,0)],['Tipo de cliente',query.customerType??'Todos'],['Total desde',query.minTotal??'Sin mínimo'],['Total hasta',query.maxTotal??'Sin máximo'],['Estado',query.status||'Todos'],['Producto',query.product||'Todos'],['Usuario',query.user||'Todos']]);summary.getRow(1).font={bold:true,size:14,color:{argb:'FF17363B'}};summary.getCell('B4').numFmt='$ #,##0.00';summary.getCell('B5').numFmt='$ #,##0.00';sheet.columns=[{header:'Fecha',key:'date',width:13},{header:'Orden',key:'order',width:14},{header:'Cliente',key:'customer',width:30},{header:'Razón social',key:'legalName',width:30},{header:'Tipo de cliente',key:'customerType',width:20},{header:'Producto',key:'product',width:24},{header:'Trabajo',key:'work',width:55},{header:'Total',key:'total',width:16},{header:'Saldo',key:'balance',width:16},{header:'Estado',key:'status',width:18},{header:'Usuario',key:'user',width:18},{header:'Fecha de entrega',key:'deliveryDate',width:18}];sheet.addRows(rows);sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:'A1',to:'L1'};sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF167D78'}};sheet.getColumn('total').numFmt='$ #,##0.00';sheet.getColumn('balance').numFmt='$ #,##0.00';const buffer=await workbook.xlsx.writeBuffer();res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition','attachment; filename="rojas-ventas-filtradas.xlsx"');res.setHeader('Content-Length',buffer.byteLength);res.end(Buffer.from(buffer))}catch(error){next(error)}});
dataRouter.get('/sales',async(req,res,next)=>{try{const query=salesQuerySchema.parse(req.query);const period=resolvePeriod(await salesRepository.list(),query).current;res.json(await service.salesList({...query,period}))}catch(error){next(error)}});
dataRouter.get('/customers',async(req,res,next)=>{try{res.json(await service.customers(await currentPeriod(req.query)))}catch(error){next(error)}});
dataRouter.get('/products',async(req,res,next)=>{try{res.json(await service.products(await currentPeriod(req.query)))}catch(error){next(error)}});
dataRouter.get('/analytics',async(req,res,next)=>{try{res.json(await service.analytics(await currentPeriod(req.query)))}catch(error){next(error)}});
dataRouter.get('/production',async(req,res,next)=>{try{const deliveryDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().parse(req.query.deliveryDate);res.json(await service.production(await currentPeriod(req.query),deliveryDate))}catch(error){next(error)}});
dataRouter.get('/forecasts',async(req,res,next)=>{try{const horizon=z.coerce.number().int().min(1).max(6).default(3).parse(req.query.horizon);res.json(await forecasts.forecast(horizon))}catch(error){next(error)}});
dataRouter.get('/reports/executive.pdf',async(req,res,next)=>{try{const query=periodQuerySchema.parse(req.query),pdf=await reports.executive(query);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="rojas-informe-${query.period}.pdf"`);res.setHeader('Content-Length',pdf.length);res.end(pdf)}catch(error){next(error)}});
dataRouter.get('/analytics/clients',async(req,res,next)=>{try{const query=periodQuerySchema.parse(req.query);const inactiveDays=z.coerce.number().int().min(1).max(730).default(90).parse(req.query.inactiveDays);res.json(await clientIntelligence.summary(query,inactiveDays))}catch(error){next(error)}});
dataRouter.get('/analytics/clients/:name',async(req,res,next)=>{try{const result=await clientIntelligence.detail(req.params.name,periodQuerySchema.parse(req.query));if(!result)return res.status(404).json({message:'Cliente no encontrado'});res.json(result)}catch(error){next(error)}});
