import { useCallback,useEffect,useState } from 'react';
import { ArrowRight,CalendarDays,CircleDollarSign,Clock3,Download,FileText,Receipt,RefreshCw,Sparkles,Users } from 'lucide-react';
import { Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { api } from '../services/api'; import type { DashboardData } from '../types/dashboard'; import { KpiCard } from '../components/KpiCard';
import { useNavigate } from 'react-router-dom';
import { useGlobalDate } from '../contexts/GlobalDateContext'; import { LoadingState,ErrorState,EmptyState } from '../components/states';
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v);
const pieColors=['#167d78','#e8a23b','#6d9fa1','#c86449','#a9b5b4'];
const dateLabel=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric'});
export function DashboardPage(){
 const navigate=useNavigate();
 const {queryString}=useGlobalDate();
 const[data,setData]=useState<DashboardData|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false),[reportBusy,setReportBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);setError('');try{setData(await api.dashboard(queryString))}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar')}finally{setBusy(false)}},[queryString]);useEffect(()=>{load()},[load]);
 const downloadReport=async()=>{setReportBusy(true);try{const blob=await api.downloadReport(queryString),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rojas-informe-gerencial.pdf';a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:'No se pudo generar el informe')}finally{setReportBusy(false)}};
 if(error)return <main className="page"><ErrorState message={error} retry={load}/></main>;
 if(!data)return <main className="page"><LoadingState/></main>;
 if(!data.recordCount)return <main className="page"><EmptyState/></main>;
 return <main className="page">
  <div className="page-heading"><div><span className="eyebrow">PERÍODO {dateLabel(data.period.from)} — {dateLabel(data.period.to)}</span><h1>Buenos días, Administrador.</h1><p>Esto es lo que está pasando en Rojas Impresiones.</p></div><div className="heading-actions"><span className="period-control"><CalendarDays/> Mes actual del archivo</span><button className="secondary-button" onClick={downloadReport} disabled={reportBusy}><Download/> {reportBusy?'Generando…':'Informe PDF'}</button><button className="secondary-button" onClick={load} disabled={busy}><RefreshCw className={busy?'spin':''}/> Actualizar</button><button className="primary-button compact-button" onClick={()=>navigate('/datos')}>IMPORTAR EXCEL <ArrowRight/></button></div></div>
  <div className="data-status"><span className="pulse"></span><strong>Datos reales analizados</strong><span>{data.recordCount.toLocaleString('es-AR')} operaciones</span><i>•</i><span>Fuente: {data.sourceLabel}</span><i>•</i><span>Archivo: {new Date(data.updatedAt).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'})}</span></div>
  <section className="kpi-grid"><KpiCard label="FACTURACIÓN" value={money(data.kpis.revenue)} change={data.kpis.revenueVariation} detail="vs. período equivalente anterior" icon={CircleDollarSign}/><KpiCard label="ÓRDENES" value={data.kpis.orders.toLocaleString('es-AR')} change={data.kpis.ordersVariation} detail="operaciones del período" icon={Receipt} tone="blue"/><KpiCard label="TICKET PROMEDIO" value={money(data.kpis.averageTicket)} change={data.kpis.averageTicketVariation} detail="vs. período equivalente anterior" icon={FileText} tone="amber"/><KpiCard label="SALDO PENDIENTE" value={money(data.kpis.outstanding)} change={data.kpis.outstandingVariation} detail={`${data.kpis.revenue?((data.kpis.outstanding/data.kpis.revenue)*100).toFixed(1):0}% de la facturación`} icon={Clock3} tone="red"/><KpiCard label="CLIENTES ACTIVOS" value={data.kpis.activeCustomers.toLocaleString('es-AR')} change={data.kpis.activeCustomersVariation} detail="clientes únicos del período" icon={Users} tone="violet"/></section>
  <section className="dashboard-grid">
   <article className="panel sales-panel"><div className="panel-head"><div><span className="panel-kicker">RENDIMIENTO COMERCIAL</span><h2>Evolución mensual de facturación</h2></div><span className="trend-pill">{data.kpis.revenueVariation>=0?'+':''}{data.kpis.revenueVariation.toLocaleString('es-AR')}% vs. período equivalente</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.salesTrend}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#167d78" stopOpacity={.3}/><stop offset="95%" stopColor="#167d78" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5eae8"/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`$${v}M`}/><Tooltip formatter={v=>[`$${v} M`,'Facturación']}/><Area type="monotone" dataKey="value" stroke="#167d78" strokeWidth={3} fill="url(#sales)"/></AreaChart></ResponsiveContainer></div></article>
   <article className="panel insight-panel"><div className="panel-head"><div><span className="panel-kicker"><Sparkles/> INSIGHTS AUTOMÁTICOS</span><h2>Lo importante del período</h2></div></div><div className="insight-list">{data.insights.map(insight=><div key={insight.title}><span className={`insight-icon ${insight.type==='positive'?'up':insight.type}`}>{insight.type==='positive'?'↗':insight.type==='alert'?'!':'✦'}</span><p><strong>{insight.title}</strong><small>{insight.detail}</small></p></div>)}</div><div className="evidence-note">Basado en {data.recordCount.toLocaleString('es-AR')} operaciones verificadas</div></article>
   <article className="panel"><div className="panel-head"><div><span className="panel-kicker">RANKING POR FACTURACIÓN</span><h2>Top clientes</h2></div></div><div className="chart-wrap short"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.topCustomers} layout="vertical" margin={{left:20}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} width={110}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="value" fill="#167d78" radius={[0,5,5,0]} barSize={14}/></BarChart></ResponsiveContainer></div></article>
   <article className="panel"><div className="panel-head"><div><span className="panel-kicker">DISTRIBUCIÓN POR FACTURACIÓN</span><h2>Productos vendidos</h2></div></div><div className="product-chart"><ResponsiveContainer width="52%" height={210}><PieChart><Pie data={data.topProducts} dataKey="value" innerRadius={55} outerRadius={82} paddingAngle={3}>{data.topProducts.map((_,i)=><Cell key={i} fill={pieColors[i]}/>)}</Pie><Tooltip formatter={v=>`${v}%`}/></PieChart></ResponsiveContainer><div className="legend">{data.topProducts.map((item,i)=><div key={item.name}><span style={{background:pieColors[i]}}></span><p>{item.name}<strong>{item.value.toLocaleString('es-AR')}%</strong></p></div>)}</div></div></article>
  </section>
  <section className="ai-cta"><div className="ai-cta-icon"><Sparkles/></div><div><span>ANÁLISIS DETERMINÍSTICO</span><h2>Números calculados desde la exportación</h2><p>No se enviaron datos a OpenAI ni se utilizaron valores demostrativos.</p></div><button className="primary-button" onClick={()=>navigate('/datos')}>VER ARCHIVO E IMPORTAR <ArrowRight/></button></section>
 </main>
}
