import { ChangeEvent,DragEvent,useRef,useState } from 'react';import { AlertTriangle,ArrowRight,CheckCircle2,FileSpreadsheet,RefreshCw,UploadCloud,X } from 'lucide-react';import { useNavigate } from 'react-router-dom';import { api,type ImportPreview } from '../services/api';
const money=(value:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value);const size=(bytes:number)=>`${(bytes/1024/1024).toFixed(2)} MB`;
export function ImportPage(){const input=useRef<HTMLInputElement>(null);const navigate=useNavigate();const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<ImportPreview|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState('');
 async function select(selected?:File){if(!selected)return;setFile(selected);setPreview(null);setDone('');setError('');setBusy(true);try{setPreview(await api.previewImport(selected))}catch(e){setError(e instanceof Error?e.message:'No se pudo leer el archivo')}finally{setBusy(false)}}
 function drop(event:DragEvent){event.preventDefault();select(event.dataTransfer.files[0])}function change(event:ChangeEvent<HTMLInputElement>){select(event.target.files?.[0])}
 async function confirm(){if(!preview)return;setBusy(true);setError('');try{const result=await api.confirmImport(preview.token);setDone(`${result.records.toLocaleString('es-AR')} operaciones importadas correctamente.`)}catch(e){setError(e instanceof Error?e.message:'No se pudo confirmar la importación')}finally{setBusy(false)}}
 function reset(){setFile(null);setPreview(null);setError('');setDone('');if(input.current)input.current.value=''}
 return <main className="page import-page"><div className="page-heading"><div><span className="eyebrow">DATOS / IMPORTAR</span><h1>Importar exportación de ventas</h1><p>Revisá la información antes de reemplazar el análisis actual.</p></div></div>
  {!preview&&!done&&<section className={`upload-zone ${busy?'busy':''}`} onDragOver={e=>e.preventDefault()} onDrop={drop}><input ref={input} type="file" accept=".xlsx,.csv" onChange={change} hidden/><div className="upload-icon">{busy?<RefreshCw className="spin"/>:<UploadCloud/>}</div><h2>{busy?'Validando archivo…':'Arrastrá el Excel exportado acá'}</h2><p>o seleccioná un archivo desde tu computadora</p><button className="primary-button upload-button" onClick={()=>input.current?.click()} disabled={busy}>SELECCIONAR ARCHIVO</button><small>Formatos admitidos: .xlsx y .csv · máximo 25 MB</small></section>}
  {error&&<div className="import-message error"><AlertTriangle/><div><strong>No se pudo procesar el archivo</strong><p>{error}</p></div><button onClick={reset}><X/></button></div>}
  {preview&&!done&&<><section className="import-file"><div className="file-icon"><FileSpreadsheet/></div><div><strong>{preview.originalName}</strong><small>{size(preview.size)} · Hoja: {preview.sheetName}</small></div><span className="valid-badge"><CheckCircle2/> Estructura válida</span><button className="icon-button" onClick={reset}><X/></button></section>
   {preview.alreadyImported&&<div className="import-message warning"><AlertTriangle/><div><strong>Este archivo ya fue importado</strong><p>Podés confirmarlo nuevamente; el análisis no duplicará operaciones.</p></div></div>}
   {preview.errorCount>0&&<div className="import-message warning"><AlertTriangle/><div><strong>{preview.errorCount} {preview.errorCount===1?'fila será rechazada':'filas serán rechazadas'}</strong>{preview.errors.map((message,index)=><p key={index}>{message}</p>)}<p>Las {preview.validRecords.toLocaleString('es-AR')} filas válidas sí se importarán.</p></div></div>}
   <section className="import-summary"><article><span>REGISTROS</span><strong>{preview.records.toLocaleString('es-AR')}</strong><small>filas detectadas</small></article><article><span>VÁLIDOS</span><strong>{preview.validRecords.toLocaleString('es-AR')}</strong><small>listos para analizar</small></article><article><span>DUPLICADOS</span><strong>{preview.duplicates.toLocaleString('es-AR')}</strong><small>según PV + Número</small></article><article><span>ERRORES</span><strong className={preview.errorCount?'danger':''}>{preview.errorCount.toLocaleString('es-AR')}</strong><small>filas rechazadas</small></article></section>
   <section className="panel import-preview"><div className="panel-head"><div><span className="panel-kicker">PREVISUALIZACIÓN</span><h2>Primeras operaciones detectadas</h2></div><span className="period-chip">{preview.dateFrom} — {preview.dateTo}</span></div><div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Orden</th><th>Cliente</th><th>Producto</th><th>Total</th><th>Saldo</th><th>Estado</th><th>Usuario</th></tr></thead><tbody>{preview.sample.map(row=><tr key={`${row.pv}-${row.numero}`}><td>{row.fecha}</td><td>{row.pv}-{row.numero}</td><td>{row.cliente}</td><td>{row.producto}</td><td>{money(row.total)}</td><td>{money(row.saldo)}</td><td><span className="status-chip">{row.estado}</span></td><td>{row.usuario}</td></tr>)}</tbody></table></div></section>
   <div className="import-actions"><button className="secondary-button" onClick={reset}>CANCELAR</button><button className="primary-button confirm-button" disabled={busy||preview.validRecords===0} onClick={confirm}>{busy?'IMPORTANDO ARCHIVO…':'CONFIRMAR E IMPORTAR'}<ArrowRight/></button></div></>}
  {done&&<section className="import-success"><CheckCircle2/><span className="eyebrow">IMPORTACIÓN COMPLETADA</span><h2>Los datos ya están listos</h2><p>{done} El dashboard fue recalculado con esta exportación.</p><div><button className="secondary-button" onClick={reset}>IMPORTAR OTRO ARCHIVO</button><button className="primary-button confirm-button" onClick={()=>navigate('/')}>VER ANÁLISIS <ArrowRight/></button></div></section>}
 </main>}
