export type AdditionalMetricDefinition={id:string;name:string;description:string;formula:string;requiredFields:string[];dimensions:string[];unit:string;limitations:string[]};

export const additionalMetricRegistry:AdditionalMetricDefinition[]=[
 {id:'advanced.absolute_change',name:'Cambio absoluto',description:'Diferencia entre el valor actual y el comparado.',formula:'current - previous',requiredFields:['Fecha','Total'],dimensions:['período'],unit:'misma unidad de la métrica',limitations:['No explica por sí solo la causa del cambio.']},
 {id:'advanced.percentage_change',name:'Variación porcentual',description:'Cambio relativo respecto del valor comparado.',formula:'(current - previous) / abs(previous) * 100',requiredFields:['Fecha','Total'],dimensions:['período'],unit:'porcentaje',limitations:['No se calcula cuando el valor anterior es cero.']},
 {id:'advanced.change_contribution',name:'Contribución al cambio',description:'Aporte de cada entidad al cambio neto total.',formula:'entityAbsoluteChange / totalAbsoluteChange * 100',requiredFields:['Fecha','Total'],dimensions:['Cliente','Producto','Usuario','Estado','PV'],unit:'porcentaje',limitations:['Puede superar 100% cuando aportes positivos y negativos se compensan.']},
 {id:'advanced.recency_ratio',name:'Recencia relativa',description:'Compara la ausencia actual con el intervalo habitual de compra.',formula:'DaysSinceLastPurchase / HistoricalAveragePurchaseInterval',requiredFields:['Fecha','Cliente'],dimensions:['Cliente'],unit:'ratio',limitations:['Requiere al menos dos fechas de compra diferentes.']},
 {id:'advanced.purchase_regularity',name:'Regularidad de compra',description:'Variabilidad de los intervalos históricos de compra.',formula:'stddev(intervalDays) / mean(intervalDays)',requiredFields:['Fecha','Cliente'],dimensions:['Cliente'],unit:'coeficiente',limitations:['Requiere al menos dos intervalos.']},
 {id:'advanced.customer_value_score',name:'Customer Value Score',description:'Score descriptivo de valor con pesos visibles.',formula:'weighted(normalizedRevenue, normalizedFrequency, normalizedTicket, inverseNormalizedRecency)',requiredFields:['Fecha','Cliente','Total'],dimensions:['Cliente'],unit:'0-100',limitations:['No representa rentabilidad ni probabilidad futura.']},
 {id:'advanced.customer_attention_score',name:'Customer Attention Score',description:'Prioridad gerencial descriptiva y explicable.',formula:'weighted(historicalImportance, recentDecline, relativeRecency, frequencyDecline, positiveBalance)',requiredFields:['Fecha','Cliente','Total','Saldo'],dimensions:['Cliente'],unit:'0-100',limitations:['No es riesgo crediticio ni probabilidad de pérdida.']},
 {id:'advanced.gini',name:'Coeficiente de Gini',description:'Desigualdad descriptiva de una distribución no negativa.',formula:'2*sum(i*x_i)/(n*sum(x))-(n+1)/n',requiredFields:['Total'],dimensions:['Cliente','Producto','Saldo positivo por cliente'],unit:'0-1',limitations:['No constituye diagnóstico automático.']},
 {id:'advanced.product_hhi',name:'HHI de productos',description:'Concentración de facturación entre productos.',formula:'sum(productRevenueShare^2)',requiredFields:['Producto','Total'],dimensions:['Producto'],unit:'0-1 y 0-10000',limitations:['No constituye diagnóstico automático.']},
 {id:'advanced.positive_balance_hhi',name:'HHI de saldo positivo',description:'Concentración del saldo registrado positivo neto por cliente.',formula:'sum(positiveCustomerBalanceShare^2)',requiredFields:['Cliente','Saldo'],dimensions:['Cliente'],unit:'0-1 y 0-10000',limitations:['Saldo positivo no implica mora.']}
];
