import type { SalesRecord,SalesRepository } from '../repositories/types.js';
import { ClientIntelligenceService } from '../services/ClientIntelligenceService.js';
import { resolvePeriod,type PeriodQuery } from '../utils/period.js';
import { defaultAttentionWeights,defaultValueWeights,type AttentionWeights,type ScoreWeights } from './AdvancedAnalyticsTypes.js';
import { coefficientOfVariation,daysBetween,filterPeriod,mean,median,normalizeWeights,percentageChange,percentileRank,periodDays,round,standardDeviation } from './StatisticalUtils.js';

type Options={limit?:number;search?:string;inactiveDays?:number;valueWeights?:Partial<ScoreWeights>;attentionWeights?:Partial<AttentionWeights>};
const group=(rows:SalesRecord[])=>{const result=new Map<string,SalesRecord[]>();for(const row of rows)result.set(row.customer,[...(result.get(row.customer)??[]),row]);return result};
const revenue=(rows:SalesRecord[])=>rows.reduce((total,row)=>total+row.total,0);
const balance=(rows:SalesRecord[])=>rows.reduce((total,row)=>total+row.balance,0);
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const purchaseDates=(rows:SalesRecord[])=>[...new Set(rows.map(row=>iso(row.date)))].sort().map(value=>new Date(value+'T00:00:00'));
const intervals=(dates:Date[])=>dates.slice(1).map((date,index)=>daysBetween(date,dates[index]!));
const mainProduct=(rows:SalesRecord[])=>{const products=new Map<string,number>();for(const row of rows)products.set(row.product,(products.get(row.product)??0)+row.total);return[...products].sort((a,b)=>b[1]-a[1])[0]?.[0]??null};
const extendedSegment=(segment:string)=>segment==='Perdidos'?'Inactivos':segment;

export class AdvancedCustomerAnalyticsService{
 private existing:ClientIntelligenceService;
 constructor(private sales:SalesRepository){this.existing=new ClientIntelligenceService(sales)}

 async analyze(query:PeriodQuery,options:Options={}){
	  const all=await this.sales.list(),periods=resolvePeriod(all,query),current=filterPeriod(all,{from:periods.current.from!,to:periods.current.to!}),previous=periods.comparison?filterPeriod(all,{from:periods.comparison.from!,to:periods.comparison.to!}):[],analysisEnd=new Date(periods.current.to!+'T23:59:59'),history=all.filter(row=>row.date<=analysisEnd),currentGroups=group(current),previousGroups=group(previous),historyGroups=group(history),existing=await this.existing.summary(query,options.inactiveDays??90),existingByName=new Map(existing.clients.map(client=>[client.name,client])),currentDays=periodDays({from:periods.current.from!,to:periods.current.to!}),previousDays=periods.comparison?periodDays({from:periods.comparison.from!,to:periods.comparison.to!}):currentDays,inactiveDays=Math.max(1,options.inactiveDays??90);
	  const names=[...new Set([...currentGroups.keys(),...previousGroups.keys()])],raw=names.map(name=>{
	   const cur=currentGroups.get(name)??[],prev=previousGroups.get(name)??[],hist=(historyGroups.get(name)??[]).slice().sort((a,b)=>a.date.getTime()-b.date.getTime()),dates=purchaseDates(hist),gaps=intervals(dates),currentRevenue=revenue(cur),previousRevenue=revenue(prev),currentOrders=cur.length,previousOrders=prev.length,currentTicket=currentOrders?currentRevenue/currentOrders:0,previousTicket=previousOrders?previousRevenue/previousOrders:0,averageInterval=mean(gaps),intervalCv=coefficientOfVariation(gaps),daysSinceLastPurchase=dates.length?daysBetween(analysisEnd,dates.at(-1)!):0,recencyRatio=averageInterval>0?daysSinceLastPurchase/averageInterval:null,activeMonths=new Set(hist.map(row=>`${row.date.getFullYear()}-${row.date.getMonth()+1}`)).size,currentFrequencyPer30=currentOrders/currentDays*30,previousFrequencyPer30=previousOrders/previousDays*30,firstPurchase=dates.length?iso(dates[0]!):null;
	   const returnHit=dates.slice(1).map((date,index)=>({date,gap:daysBetween(date,dates[index]!)})).find(item=>item.gap>=inactiveDays&&iso(item.date)>=periods.current.from!&&iso(item.date)<=periods.current.to!),beforeReturn=returnHit?hist.filter(row=>row.date<returnHit.date):[],afterReturn=returnHit?hist.filter(row=>row.date>=returnHit.date&&row.date<=analysisEnd):[];
	   return{name,fantasyName:hist.find(row=>row.fantasyName)?.fantasyName??name,currentRevenue:round(currentRevenue),previousRevenue:round(previousRevenue),absoluteChange:round(currentRevenue-previousRevenue),percentageChange:percentageChange(currentRevenue,previousRevenue)===null?null:round(percentageChange(currentRevenue,previousRevenue)!),currentOrders,previousOrders,ordersChange:currentOrders-previousOrders,currentTicket:round(currentTicket),previousTicket:round(previousTicket),ticketChange:round(currentTicket-previousTicket),medianTicket:round(median(cur.map(row=>row.total))),share:0,balanceRegistered:round(balance(cur)),firstPurchase,lastPurchase:dates.length?iso(dates.at(-1)!):null,isNew:Boolean(firstPurchase&&firstPurchase>=periods.current.from!&&firstPurchase<=periods.current.to!),recovered:returnHit?{returnDate:iso(returnHit.date),inactiveDays:returnHit.gap,revenueBeforeReturn:round(revenue(beforeReturn)),revenueAfterReturn:round(revenue(afterReturn)),ordersAfterReturn:afterReturn.length,productsAfterReturn:[...new Set(afterReturn.map(row=>row.product))]}:null,daysSinceLastPurchase,distinctProducts:new Set(cur.map(row=>row.product)).size,mainProduct:mainProduct(cur),historicalRevenue:round(revenue(hist)),historicalOrders:hist.length,purchasesPerActiveMonth:activeMonths?round(hist.length/activeMonths):0,averagePurchaseIntervalDays:gaps.length?round(averageInterval):null,medianPurchaseIntervalDays:gaps.length?round(median(gaps)):null,purchaseIntervalStdDevDays:gaps.length>1?round(standardDeviation(gaps)):null,purchaseIntervalCv:intervalCv===null?null:round(intervalCv),regularity:gaps.length<2?'INSUFFICIENT':intervalCv!<=.5?'ALTA':intervalCv!<=1?'MEDIA':'BAJA',recencyRatio:recencyRatio===null?null:round(recencyRatio),currentFrequencyPer30Days:round(currentFrequencyPer30),previousFrequencyPer30Days:round(previousFrequencyPer30),frequencyChange:round(currentFrequencyPer30-previousFrequencyPer30),frequencyChangePercent:percentageChange(currentFrequencyPer30,previousFrequencyPer30)===null?null:round(percentageChange(currentFrequencyPer30,previousFrequencyPer30)!),existingRfm:existingByName.get(name)?.rfm??null,extendedRfmSegment:extendedSegment(existingByName.get(name)?.rfm.segment??'Inactivos')};
	  });
  const totalRevenue=revenue(current),totalChange=totalRevenue-revenue(previous);for(const item of raw)item.share=totalRevenue?round(item.currentRevenue/totalRevenue*100):0;
  const valueWeights=normalizeWeights({...defaultValueWeights,...options.valueWeights}),attentionWeights=normalizeWeights({...defaultAttentionWeights,...options.attentionWeights}),revenueValues=raw.map(item=>item.currentRevenue),frequencyValues=raw.map(item=>item.currentOrders),ticketValues=raw.map(item=>item.currentTicket),recencyValues=raw.map(item=>item.daysSinceLastPurchase),historicalValues=raw.map(item=>item.historicalRevenue),declineValues=raw.map(item=>Math.max(0,-item.absoluteChange)),positiveBalances=raw.map(item=>Math.max(0,item.balanceRegistered));
  const scored=raw.map(item=>{const valueComponents={revenue:percentileRank(item.currentRevenue,revenueValues),frequency:percentileRank(item.currentOrders,frequencyValues),ticket:percentileRank(item.currentTicket,ticketValues),recency:percentileRank(item.daysSinceLastPurchase,recencyValues,true)},frequencyDecline=item.previousFrequencyPer30Days>0?Math.max(0,(item.previousFrequencyPer30Days-item.currentFrequencyPer30Days)/item.previousFrequencyPer30Days*100):0,attentionComponents={historicalImportance:percentileRank(item.historicalRevenue,historicalValues),recentDecline:percentileRank(Math.max(0,-item.absoluteChange),declineValues),relativeRecency:Math.min(100,(item.recencyRatio??0)/3*100),frequencyDecline:Math.min(100,frequencyDecline),positiveBalance:percentileRank(Math.max(0,item.balanceRegistered),positiveBalances)},valueScore=Object.entries(valueComponents).reduce((total,[key,value])=>total+value*valueWeights[key as keyof ScoreWeights],0),attentionScore=Object.entries(attentionComponents).reduce((total,[key,value])=>total+value*attentionWeights[key as keyof AttentionWeights],0);return{...item,contributionToTotalChange:totalChange===0?null:round(item.absoluteChange/totalChange*100),customerValueScore:{value:round(valueScore),weights:valueWeights,components:Object.fromEntries(Object.entries(valueComponents).map(([key,value])=>[key,round(value)])),formula:'weighted(normalizedRevenue, normalizedFrequency, normalizedTicket, inverseNormalizedRecency)'},customerAttentionScore:{value:round(attentionScore),weights:attentionWeights,components:Object.fromEntries(Object.entries(attentionComponents).map(([key,value])=>[key,round(value)])),formula:'weighted(historicalImportance, recentDecline, relativeRecency, frequencyDecline, positiveBalance)',warning:'Indicador gerencial descriptivo; no es riesgo crediticio ni probabilidad de pérdida.'}}}).filter(item=>!options.search||(item.name+' '+item.fantasyName).toLocaleLowerCase('es').includes(options.search.toLocaleLowerCase('es'))).sort((a,b)=>b.currentRevenue-a.currentRevenue),limit=Math.min(1000,Math.max(1,options.limit??100));
	  const newCustomers=scored.filter(item=>item.isNew),recoveredCustomers=scored.filter(item=>item.recovered),newRevenue=newCustomers.reduce((sum,item)=>sum+item.currentRevenue,0),newOrders=newCustomers.reduce((sum,item)=>sum+item.currentOrders,0);
	  return{source:this.sales.getSourceLabel(),period:{from:periods.current.from!,to:periods.current.to!},comparisonPeriod:periods.comparison?{from:periods.comparison.from!,to:periods.comparison.to!}:null,filters:{...query,search:options.search??'',limit,inactiveDays},recordsUsed:current.length,comparisonRecordsUsed:previous.length,totalCustomers:scored.length,newCustomers:{count:newCustomers.length,revenue:round(newRevenue),share:totalRevenue?round(newRevenue/totalRevenue*100):0,averageTicket:newOrders?round(newRevenue/newOrders):0,products:[...new Set(newCustomers.flatMap(item=>currentGroups.get(item.name)?.map(row=>row.product)??[]))]},recoveredCustomers:{count:recoveredCustomers.length,inactiveDays,details:recoveredCustomers.map(item=>({name:item.name,fantasyName:item.fantasyName,...item.recovered})).slice(0,limit)},customers:scored.slice(0,limit),detailsIncluded:Math.min(limit,scored.length),metricEvidence:{recencyRatio:{sourceFields:['Fecha','Cliente'],formula:'DaysSinceLastPurchase / HistoricalAveragePurchaseInterval',method:'Intervalos entre días únicos de compra.',limitations:['Requiere al menos dos fechas de compra diferentes.']},frequency:{sourceFields:['Fecha','Cliente'],formula:'Operaciones / días del período * 30',method:'Frecuencia normalizada a 30 días.',limitations:['Operaciones no equivale a unidades físicas.']},newCustomers:{sourceFields:['Fecha','Cliente','Total','Producto'],formula:'Primera compra histórica dentro del período actual.',method:'Se revisa el historial disponible hasta el cierre del período.',limitations:['La condición de nuevo depende del alcance histórico del archivo.']},recoveredCustomers:{sourceFields:['Fecha','Cliente','Total','Producto'],formula:'Nueva compra después de un intervalo >= inactiveDays.',method:'Intervalos entre días únicos de compra; umbral configurable.',limitations:['Un regreso describe actividad observada, no permanencia futura.']},customerValueScore:{sourceFields:['Fecha','Cliente','Total'],formula:'Score ponderado con componentes normalizados por percentil.',method:'Pesos configurables y visibles.',limitations:['No mide rentabilidad.']},customerAttentionScore:{sourceFields:['Fecha','Cliente','Total','Saldo'],formula:'Score ponderado de importancia, caída, recencia relativa, frecuencia y saldo positivo.',method:'Indicador descriptivo con pesos visibles.',limitations:['No es riesgo crediticio ni probabilidad de pérdida.']}}};
 }
}
